language: r
env:
    global:
        - _R_CHECK_TIMINGS_=0

warnings_are_errors: true
apt_packages:
    - r-cran-rjava
r_github_packages:
    - OpenML/r
before_script:
    - sudo R CMD javareconf
notifications:
  email:
    recipients:
        - bernd_bischl@gmx.net
    on_success: change
    on_failure: always

env:
  global:
  - secure: oBSw3lt+e3/iEEhYHXEAJpZWmITbC6HtqRVXIKQsVpaGfQ6zxxoIKeUOpSUGSGvG+CLBqie97a7eWDq2Z21md6wr+jBnmAoHlrUckQdw7GF8aT3aOmZzQ6cZbQniTn5nRJ8GlfYi/nkhxIDQ0bUY3KBBUak27uHvNEY4wqSdCxE=
   

